# Generated by Django 5.0 on 2024-02-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_graduation_name_alter_graduation_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
        migrations.RenameField(
            model_name='graduation',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='description',
        ),
    ]
