# Generated by Django 5.0.2 on 2024-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_email_alter_user_password_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='Last_Name',
        ),
        migrations.AddField(
            model_name='booking',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Location',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='Phone_no',
            field=models.BigIntegerField(default=23),
            preserve_default=False,
        ),
    ]
