# Generated by Django 5.0.2 on 2024-02-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_amount_booking_last_name_booking_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='First_Name',
        ),
    ]
