# Generated by Django 5.0.2 on 2024-02-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_name_booking_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Category_Id',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_id',
            new_name='Package',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='subcat_id',
            new_name='subcat',
        ),
    ]
