# Generated by Django 5.0.2 on 2024-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_category_id_booking_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Package',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subcat',
            field=models.CharField(max_length=30),
        ),
    ]
