# Generated by Django 5.0.2 on 2024-03-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Payment_Id',
        ),
        migrations.AddField(
            model_name='card',
            name='Booking_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
            preserve_default=False,
        ),
    ]
