# Generated by Django 5.0.2 on 2024-03-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_card_payment_id_card_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Booking_Id',
        ),
    ]
