# Generated by Django 5.0.2 on 2024-03-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_card_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='User_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
