# Generated by Django 5.0 on 2024-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_booking_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Expiry_Date',
            field=models.CharField(max_length=10),
        ),
    ]
