# Generated by Django 5.0 on 2024-04-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_card_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
